CREATE DATABASE IF NOT EXISTS crud_notas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE crud_notas;

DROP TABLE IF EXISTS nota;
DROP TABLE IF EXISTS alumno;

CREATE TABLE alumno (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre   VARCHAR(80) NOT NULL,
  apellido VARCHAR(80) NOT NULL,
  correo   VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE nota (
  id INT AUTO_INCREMENT PRIMARY KEY,
  alumno_id INT NOT NULL,
  nota DECIMAL(4,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_nota_alumno
    FOREIGN KEY (alumno_id) REFERENCES alumno(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;
